[theme]
base = "light"
#primaryColor = "#89CFF0"
#backgroundColor = "#E0F7FE"
#secondaryBackgroundColor = "#FFFCE4"
textColor = "#000000"
font = "sans serif"


OPENAI_API_KEY = "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"